fix return code

diff --git a/root/usr/libexec/packagesync/sync b/root/usr/libexec/packagesync/sync
--- a/root/usr/libexec/packagesync/sync
+++ b/root/usr/libexec/packagesync/sync
@@ -147,7 +147,7 @@ parse_json() {
       fi
     fi
   done
-  return 0
+  return $ERROR
 }
 
 #mirror <local mirror root path> <openwrt version> <target/subtarget> <package arch>
@@ -163,11 +163,11 @@ mirror() {
   [ "$ERROR" -gt 0 ] && return 1
 
   #start sync
-  sync_package "${homedir}" "${version}" "${arch}"
-  sync_target  "${homedir}" "${version}" "${target}" "${kversion}"
-  sync_module  "${homedir}" "${version}" "${target}" "${module}"
+  sync_package "${homedir}" "${version}" "${arch}" || ((ERROR++))
+  sync_target  "${homedir}" "${version}" "${target}" "${kversion}" || ((ERROR++))
+  sync_module  "${homedir}" "${version}" "${target}" "${module}" || ((ERROR++))
 
-  return 0
+  return $ERROR
 }
 
 #sync_package <local mirror root path> <openwrt version> <package arch>
@@ -176,13 +176,17 @@ sync_package() {
   local ver="$1" && shift
   local arch="$1" && shift
 
+  local ERROR=0
+
   local VER="$URLHREF_RELEASES/$ver"
   mkdir -p "$home/${VER}" 2>/dev/null
 
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include "$URLHREF_VERS_PACKAGES" --exclude '*' "$RSYNC_URL/${VER}/" "$home/${VER}/"
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include "$URLHREF_VERS_PACKAGES" --exclude '*' "$RSYNC_URL/${VER}/" "$home/${VER}/" || ((ERROR++))
   sleep 5
   mkdir -p "$home/${VER}/$(ls -l "$home/${VER}/$URLHREF_VERS_PACKAGES" | sed "s|.*->[ ]*\(.*\)[ ]*$|\1|")" 2>/dev/null
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_PACKAGES/$arch" "$home/${VER}/$URLHREF_VERS_PACKAGES/"
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_PACKAGES/$arch" "$home/${VER}/$URLHREF_VERS_PACKAGES/" || ((ERROR++))
+
+  return $ERROR
 }
 
 #sync_target <local mirror root path> <openwrt version> <target/subtarget> [Kernel version]
@@ -192,25 +196,29 @@ sync_target() {
   local target="$1" && shift
   [ "$#" -ge 1 ] && local kver="$1" && shift
 
+  local ERROR=0
+
   local VER="$URLHREF_RELEASES/$ver"
   mkdir -p "$home/${VER}" 2>/dev/null
 
   mkdir -p "$home/${VER}/$URLHREF_VERS_TARGETS/$target" 2>/dev/null
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include '*/' --exclude '*' "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/"
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include '*/' --exclude '*' "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
   #kmods
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/kmods/$kver" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/kmods/"
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/kmods/$kver" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/kmods/" || ((ERROR++))
   #packages
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/packages" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/"
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/packages" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
   #supplementary
   local table="$(curl --connect-timeout 10 --retry 3 -sSL "$WEB_URL/${VER}/$URLHREF_VERS_TARGETS/$target" | sed -n '/Supplementary Files/,$p' | sed -n '/<table>/,/<\/table>/p')"
   if [ -n "$table" ]; then
     for v in $(echo "$table" | sed -En "s|.+\bhref=\"([^\"/]+)\".+|'\1'|gp"); do
-      rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/$v" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/"
+      rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/$v" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
     done
   else
     >&2 echo -e "$(basename $0): Sync '${VER}/$URLHREF_VERS_TARGETS/$target' error. Get Supplementary Files failed.\n\tPlease check for network"
     return 1
   fi
+
+  return $ERROR
 }
 
 #sync_module <local mirror root path> <openwrt version> <target/subtarget> <module>
@@ -220,6 +228,8 @@ sync_module() {
   local target="$1" && shift
   local module="$1" && shift
 
+  local ERROR=0
+
   #Predefined
   [ -z "$module" ] && {
     case "$target" in
@@ -228,7 +238,8 @@ sync_module() {
       ;;
       *)
         module="${target/\//-}"
-        return 1
+        #return 1
+        return 0
       ;;
     esac
   }
@@ -236,7 +247,9 @@ sync_module() {
   local VER="$URLHREF_RELEASES/$ver"
   mkdir -p "$home/${VER}" 2>/dev/null
 
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include={"$module"} --exclude '*' "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/"
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include={"$module"} --exclude '*' "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
+
+  return $ERROR
 }
 
 
@@ -321,5 +334,5 @@ done
 # ...
 
 # Execute
-parse_json "${JSON:=[{'name':'$name','version':'$version','target':'$target','arch':'$arch'\}]}" || { >&2 echo -e "$(basename $0): Required options requires valid argument\n\tUse the --help option get help"; exit 1; }
+parse_json "${JSON:=[{'name':'$name','version':'$version','target':'$target','arch':'$arch'\}]}" #|| { >&2 echo -e "$(basename $0): Required options requires valid argument\n\tUse the --help option get help"; exit 1; }
 
