model

diff --git a/root/usr/libexec/packagesync/sync b/root/usr/libexec/packagesync/sync
--- a/root/usr/libexec/packagesync/sync
+++ b/root/usr/libexec/packagesync/sync
@@ -32,7 +32,7 @@ BWLIMIT='8000'
 
 
 # Get parameters
-GETOPT=$(getopt -n $(basename $0) -o x:l:d:n:s:t:k:e:o:V -l proxy:,bwlimit:,homedir:,name:,version:,target:,arch:,extra:,orders:,Version,help -- "$@")
+GETOPT=$(getopt -n $(basename $0) -o x:l:d:n:s:t:k:e:m:o:V -l proxy:,bwlimit:,homedir:,name:,version:,target:,arch:,extra:,model:,orders:,Version,help -- "$@")
 [ $? -ne 0 ] && >&2 echo -e "\tUse the --help option get help" && exit 1
 eval set -- "$GETOPT"
 OPTIONS=$(echo "$GETOPT" | sed -E "s|'[^']*'||g; s| --( .*)?$||")
@@ -51,6 +51,7 @@ echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-s|--version)\b" >/dev
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-t|--target)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-t|--target'" && exit 1
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-k|--arch)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-k|--arch'" && exit 1
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-e|--extra)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-e|--extra'" && exit 1
+echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-m|--model)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-m|--model'" && exit 1
 # Required options
 [    -n "$(echo "$OPTIONS" | grep -E " (-d|--homedir)\b" | grep -E " (-s|--version)\b" | grep -E " (-t|--target)\b" | grep -E " (-k|--arch)\b")" \
   -o -n "$(echo "$OPTIONS" | grep -E " (-o|--orders)\b")" \
@@ -77,6 +78,7 @@ Options:\n\
   -t, --target <target/subtarget>     -- Required option. Device target and subtarget\n\
   -k, --arch <pkgarch>                -- Required option. Device architecture\n\
   -e, --extra <true|false>            -- Optional option. Sync target supplementary. Default is false\n\
+  -m, --model <model>                 -- Optional option. Product model keyword\n\
   -o, --orders <orders>               -- Required option. Sync multi-versions at once\n\
   -l, --bwlimit <n>[(K|M|G)]          -- Bandwidth limit\n\
   -x, --proxy <protocol://ip:port>    -- Connect using proxy\n\
@@ -125,7 +127,7 @@ parse_json() {
 
   for i in $(seq 0 $[ $count -1 ]); do
     local order="$(eval "jsonfilter -q -s \"\$array\" -e '\$[$i]'")"
-    local ucivv="homedir version target arch extra name"
+    local ucivv="homedir version target arch extra model name"
     for _var in $ucivv; do
       eval "local $_var=\"\$(jsonfilter -q -s \"\$order\" -e '\$.$_var')\""
     done
@@ -133,10 +135,10 @@ parse_json() {
     mkdir -p "$RESULTPATH" 2>/dev/null
     if [ -n "$name" ]; then
       cat /dev/null > "$RESULTPATH/${name}.log"
-      { mirror "$homedir" "$version" "$target" "$arch" "$extra" 2>&1 1>&3 | tee "$RESULTPATH/${name}.log"; } 3>&1 1>&2 # in bash
+      { mirror "$homedir" "$version" "$target" "$arch" "$extra" "$model" 2>&1 1>&3 | tee "$RESULTPATH/${name}.log"; } 3>&1 1>&2 # in bash
       #mirror "$homedir" "$version" "$target" "$arch" 2> >(tee "$RESULTPATH/${name}.log" >&2) # in POSIX shell
     else
-      mirror "$homedir" "$version" "$target" "$arch" "$extra"
+      mirror "$homedir" "$version" "$target" "$arch" "$extra" "$model"
     fi
     local ERROR="$?"
 
@@ -157,7 +159,7 @@ parse_json() {
   return $ERROR
 }
 
-#mirror <local mirror root path> <openwrt version> <target/subtarget> <package arch> <extra>
+#mirror <local mirror root path> <openwrt version> <target/subtarget> <package arch> <extra> <model>
 mirror() {
   local homedir version target arch extra ERROR=0
   homedir="${1:-$HOMEPATH}" && shift
@@ -165,6 +167,7 @@ mirror() {
   target="$1" && shift
   arch="$1" && shift
   extra="$1" && shift
+  model="$1" && shift
 
   verify_path "$homedir" || { >&2 echo -e "$(basename $0): No valid <homedir> specified\n\tUse the --help option get help"; ((ERROR++)); }
   verify_order "$version" "$target" "$arch" || { >&2 echo -e "$(basename $0): Order '$version' '$target' '$arch' seems invalid.\n\tPlease check for network or typos"; ((ERROR++)); }
@@ -179,9 +182,9 @@ mirror() {
   echo -e "$(basename $0): '$version' '$target' supplementary syncing..."
   sync_extra   "${homedir}" "${version}" "${target}" || ((ERROR++))
   }
-  [ -n "$module" ] && {
-  echo -e "$(basename $0): '$version' '$target' '$module' module syncing..."
-  sync_module  "${homedir}" "${version}" "${target}" "${module}" || ((ERROR++))
+  [ -n "$model" ] && {
+  echo -e "$(basename $0): '$version' '$target' '$model' model syncing..."
+  sync_model  "${homedir}" "${version}" "${target}" "${model}" || ((ERROR++))
   }
 
   return $ERROR
@@ -256,23 +259,23 @@ sync_extra() {
   return $ERROR
 }
 
-#sync_module <local mirror root path> <openwrt version> <target/subtarget> <module>
-sync_module() {
+#sync_model <local mirror root path> <openwrt version> <target/subtarget> <model>
+sync_model() {
   local home="${1%/}" && shift
   local ver="$1" && shift
   local target="$1" && shift
-  local module="$1" && shift
+  local model="$1" && shift
 
   local ERROR=0
 
   #Predefined
-  [ -z "$module" ] && {
+  [ -z "$model" ] && {
     case "$target" in
       x86/64)
-        module="x86-64"
+        model="x86-64"
       ;;
       *)
-        module="${target/\//-}"
+        model="${target/\//-}"
         #return 1
         return 0
       ;;
@@ -282,7 +285,7 @@ sync_module() {
   local VER="$URLHREF_RELEASES/$ver"
   mkdir -p "$home/${VER}" 2>/dev/null
 
-  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include={"$module"} --exclude '*' "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
+  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT --include="*${model}-*" --exclude='*' "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
 
   return $ERROR
 }
@@ -363,6 +366,10 @@ fe80:(:[[:xdigit:]]{0,4}){0,4}%\w+|\
       extra="$2"
       shift
     ;;
+    -m|--model)
+      extra="$2"
+      shift
+    ;;
     -o|--orders)
       JSON="$2"
       shift
@@ -382,7 +389,7 @@ done
 # ...
 
 # Execute
-parse_json "${JSON:=[{'name':'$name','version':'$version','target':'$target','arch':'$arch','extra':${extra:-false}\}]}" #|| { >&2 echo -e "$(basename $0): Required options requires valid argument\n\tUse the --help option get help"; exit 1; }
+parse_json "${JSON:=[{'name':'$name','version':'$version','target':'$target','arch':'$arch','extra':${extra:-false},'model':'${model}'\}]}" #|| { >&2 echo -e "$(basename $0): Required options requires valid argument\n\tUse the --help option get help"; exit 1; }
 exitcode=$?
 rm -f "$PIDFILE" 2>/dev/null
 exit $exitcode
