readability adjustments

diff --git a/root/usr/libexec/packagesync/sync b/root/usr/libexec/packagesync/sync
--- a/root/usr/libexec/packagesync/sync
+++ b/root/usr/libexec/packagesync/sync
@@ -32,7 +32,7 @@ BWLIMIT='8000'
 
 
 # Get parameters
-GETOPT=$(getopt -n $(basename $0) -o x:l:d:n:s:t:k:e:m:o:V -l proxy:,bwlimit:,homedir:,name:,version:,target:,arch:,extra:,model:,orders:,Version,help -- "$@")
+GETOPT=$(getopt -n $(basename $0) -o d:n:s:t:k:m:e:o:l:x:V -l homedir:,name:,version:,target:,arch:,model:,extra:,orders:,bwlimit:,proxy:,Version,help -- "$@")
 [ $? -ne 0 ] && >&2 echo -e "\tUse the --help option get help" && exit 1
 eval set -- "$GETOPT"
 OPTIONS=$(sed -E "s|'[^']*'||g; s| --( .*)?$||" <<< "$GETOPT")
@@ -50,8 +50,8 @@ echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-n|--name)\b" >/dev/nu
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-s|--version)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-s|--version'" && exit 1
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-t|--target)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-t|--target'" && exit 1
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-k|--arch)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-k|--arch'" && exit 1
-echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-e|--extra)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-e|--extra'" && exit 1
 echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-m|--model)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-m|--model'" && exit 1
+echo "$OPTIONS" | grep -E " (-o|--orders)\b" | grep -E " (-e|--extra)\b" >/dev/null && >&2 echo "$(basename $0): Option '-o|--orders' cannot be used with option '-e|--extra'" && exit 1
 # Required options
 [    -n "$(echo "$OPTIONS" | grep -E " (-d|--homedir)\b" | grep -E " (-s|--version)\b" | grep -E " (-t|--target)\b" | grep -E " (-k|--arch)\b")" \
   -o -n "$(echo "$OPTIONS" | grep -E " (-o|--orders)\b")" \
@@ -77,8 +77,8 @@ Options:\n\
   -s, --version <version>             -- Required option. OpenWRT version\n\
   -t, --target <target/subtarget>     -- Required option. Device target and subtarget\n\
   -k, --arch <pkgarch>                -- Required option. Device architecture\n\
-  -e, --extra <true|false>            -- Optional option. Sync target supplementary. Default is false\n\
   -m, --model <model>                 -- Optional option. Product model keyword\n\
+  -e, --extra <true|false>            -- Optional option. Sync target supplementary. Default is false\n\
   -o, --orders <orders>               -- Required option. Sync multi-versions at once\n\
   -l, --bwlimit <n>[(K|M|G)]          -- Bandwidth limit\n\
   -x, --proxy <protocol://ip:port>    -- Connect using proxy\n\
@@ -127,7 +127,7 @@ parse_json() {
 
   for i in $(seq 0 $[ $count -1 ]); do
     local order="$(eval "jsonfilter -q -s \"\$array\" -e '\$[$i]'")"
-    local ucivv="homedir version target arch extra model name"
+    local ucivv="homedir version target arch model extra name"
     for _var in $ucivv; do
       eval "local $_var=\"\$(jsonfilter -q -s \"\$order\" -e '\$.$_var')\""
     done
@@ -135,10 +135,10 @@ parse_json() {
     mkdir -p "$RESULTPATH" 2>/dev/null
     if [ -n "$name" ]; then
       cat /dev/null > "$RESULTPATH/${name}.log"
-      { mirror "$homedir" "$version" "$target" "$arch" "$extra" "$model" 2>&1 1>&3 | tee "$RESULTPATH/${name}.log"; } 3>&1 1>&2 # in bash
+      { mirror "$homedir" "$version" "$target" "$arch" "$model" "$extra" 2>&1 1>&3 | tee "$RESULTPATH/${name}.log"; } 3>&1 1>&2 # in bash
       #mirror "$homedir" "$version" "$target" "$arch" 2> >(tee "$RESULTPATH/${name}.log" >&2) # in POSIX shell
     else
-      mirror "$homedir" "$version" "$target" "$arch" "$extra" "$model"
+      mirror "$homedir" "$version" "$target" "$arch" "$model" "$extra"
     fi
     local ERROR="$?"
 
@@ -159,15 +159,15 @@ parse_json() {
   return $ERROR
 }
 
-#mirror <local mirror root path> <openwrt version> <target/subtarget> <package arch> <extra> <model>
+#mirror <local mirror root path> <openwrt version> <target/subtarget> <package arch> <model> <extra>
 mirror() {
-  local homedir version target arch extra ERROR=0
+  local homedir version target arch model extra ERROR=0
   homedir="${1:-$HOMEPATH}" && shift
   version="$1" && shift
   target="$1" && shift
   arch="$1" && shift
-  extra="$1" && shift
   model="$1" && shift
+  extra="$1" && shift
 
   verify_path "$homedir" || { >&2 echo -e "$(basename $0): No valid <homedir> specified\n\tUse the --help option get help"; ((ERROR++)); }
   verify_order "$version" "$target" "$arch" || { >&2 echo -e "$(basename $0): Order '$version' '$target' '$arch' seems invalid.\n\tPlease check for network or typos"; ((ERROR++)); }
@@ -362,12 +362,12 @@ fe80:(:[[:xdigit:]]{0,4}){0,4}%\w+|\
       arch="$2"
       shift
     ;;
-    -e|--extra)
-      extra="$2"
-      shift
-    ;;
     -m|--model)
       model="$2"
+      shift
+    ;;
+    -e|--extra)
+      extra="$2"
       shift
     ;;
     -o|--orders)
@@ -389,7 +389,7 @@ done
 # ...
 
 # Execute
-parse_json "${JSON:=[{'name':'$name','version':'$version','target':'$target','arch':'$arch','extra':${extra:-false},'model':'${model}'\}]}" #|| { >&2 echo -e "$(basename $0): Required options requires valid argument\n\tUse the --help option get help"; exit 1; }
+parse_json "${JSON:=[{'name':'$name','version':'$version','target':'$target','arch':'$arch','model':'${model}','extra':${extra:-false}\}]}" #|| { >&2 echo -e "$(basename $0): Required options requires valid argument\n\tUse the --help option get help"; exit 1; }
 exitcode=$?
 rm -f "$PIDFILE" 2>/dev/null
 exit $exitcode
